### ISSUE TITLE
resume not work

### ISSUE THREAD

**Issue by GreatV** [THU-MIG/yolov10#184]
```shell
yolo task=detect mode=train model=${PRETRAIN_MODEL_PATH} data=${DATA_CONF_PATH} \
    project=${MODEL_DIR} name=${EXP_NAME} exist_ok=True epochs=100 batch=8 \
    imgsz=640 device=0 warmup_epochs=10 mosaic=0.25 resume=True
```

```
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/project/yolov10/ultralytics/nn/tasks.py", line 93, in forward
    return self.loss(x, *args, **kwargs)
  File "/project/yolov10/ultralytics/nn/tasks.py", line 275, in loss
    return self.criterion(preds, batch)
  File "/project/yolov10/ultralytics/utils/loss.py", line 201, in __call__
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
  File "/project/yolov10/ultralytics/utils/loss.py", line 201, in <listcomp>
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
AttributeError: 'str' object has no attribute 'view'
```

**Comment by sanha9999** [comment]
Does the name of the pt file(${PRETRAIN_MODEL_PATH}) include 'yolov10'?

**Comment by GreatV** [comment]
@sanha9999  no, just 'last.pt'

**Comment by GreatV** [comment]
I think normally we need to retrain from `last.pt`, which is the default behavior of yolov8.

**Comment by jameslahm** [comment]
Thanks for your interest! We just made the `YOLOv10` by default in cli. Could you please update the codebase and try again? Thank you!

**Comment by hyperf0cus** [comment]
resume=True from CLI starts training from 1st epoch...

**Comment by zylo117** [comment]
+1, not fixed at all

**Comment by zylo117** [comment]
> resume=True from CLI starts training from 1st epoch...

same here

**Comment by GreatV** [comment]
@zylo117  you need set `model=last.pt resume=True`

**Comment by zylo117** [comment]
> @zylo117 you need set `model=last.pt resume=True`


you mean path/to/last.pt or just last.pt, the former crashs because it can't find the weight and the latter just starts from epoch 1
neither works

**Comment by sanha9999** [comment]
@zylo117 Have you tried running code updates?

**Comment by zylo117** [comment]
> @zylo117 Have you tried running code updates?

it's the latest

**Comment by sanha9999** [comment]
could you tell me the command you CLI entered?

**Comment by zylo117** [comment]
![图片](https://github.com/THU-MIG/yolov10/assets/5842006/9148deac-8eee-44d9-9573-6fad5b6deb1c)
here is some log. The resume is always none, is this normal?
I ran with `yolo detect train data=xxx.yaml model=path/to/last.pt epochs=100 batch=32 imgsa=640 device=0,1,2,3 cache=true amp=true save_period=1 plots=true resume=true`

**Comment by zylo117** [comment]
the training was working, and I think resume training can load the weight normally judging from the low loss, but the epoch starts from 1

**Comment by zylo117** [comment]
> ![图片](https://private-user-images.githubusercontent.com/5842006/337881671-9148deac-8eee-44d9-9573-6fad5b6deb1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NTgzMzgsIm5iZiI6MTcxNzg1ODAzOCwicGF0aCI6Ii81ODQyMDA2LzMzNzg4MTY3MS05MTQ4ZGVhYy04ZWVlLTQ0ZDktOTU3My02ZmFkNWI2ZGViMWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDhUMTQ0NzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2JmYTc1ZGUyYWYxMjNkNmFiYmQwYzZiOTgzMDFmYjdkYWMxZWI0NzU0Mjc4NzVlZGM4NDA0ZTRiYjJiNmUwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gfbdy8n4Su744ULaWd_i3Mwbn6c7Ik8noJYwTxUbEPk) here is some log. The resume is always none, is this normal? I ran with `yolo detect train data=xxx.yaml model=path/to/last.pt epochs=100 batch=32 imgsz=640 device=0,1,2,3 cache=true amp=true save_period=1 plots=true resume=true`

![图片](https://github.com/THU-MIG/yolov10/assets/5842006/090b9701-e4f0-47fb-a107-3f95ba32125b)

the epoch starts from 1 even though I set model=path/to/last.pt and resume=true

**Comment by sanha9999** [comment]
could you change command
```
resume=true -> resume=True
```

**Comment by zylo117** [comment]
> could you change command?
> 
> ```
> resume=true -> resume=True
> ```

I try true and True, it's the same

**Comment by zylo117** [comment]
![337881671-9148deac-8eee-44d9-9573-6fad5b6deb1c](https://github.com/THU-MIG/yolov10/assets/5842006/61a00dd2-f6b5-4753-aa8d-0b20c7d7c527)
I think this is why resume not working, but I dont know how. resume is none here. even though i set model and resume

**Comment by GreatV** [comment]
@zylo117  you may try set `exist_ok=True`

**Comment by zylo117** [comment]
> ![图片](https://private-user-images.githubusercontent.com/5842006/337899381-393a8cfb-c85f-49d8-ab4f-3ea606052d3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NjE1NDAsIm5iZiI6MTcxNzg2MTI0MCwicGF0aCI6Ii81ODQyMDA2LzMzNzg5OTM4MS0zOTNhOGNmYi1jODVmLTQ5ZDgtYWI0Zi0zZWE2MDYwNTJkM2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDhUMTU0MDQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDVkZTUzNGJiYTE0YWNiZmVlODQ1NzRlZTYyZDg1Y2NmYzk4NzVlMTVkNTRiZWI0YWFhYTViODY1ZmFjNDAzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HSbuR4z8aQyTFMeOGgetpV9P7JRSauI7LNEmgYzGUIE) after a lot of debug, find out somehow the self.resume here became None, but ckpt is the weight

well, I have to force self.resume to be True here and it's fixed. Now it can resume training. ultralytics is just too damn unreliable. And the coco annotaion convert is just unnecessary and the whole framework seems to work for one single dataset. I recommend mmdetection, it is a highly stable and customizable framework, I really wish you can impl your next work on it. 

@hyperf0cus you can try my solution

**Comment by hyperf0cus** [comment]
@zylo117 Now it's resume, but this approach so strange and abnormal)

**Comment by leonnil** [comment]
Hi everyone! we found that this problem has been fixed in ultralytics v8.1.41 (https://github.com/ultralytics/ultralytics/pull/9453), but yolov10 is based on v8.1.34. So we fixed this manually in our codebase. Please update the code to the latest version. Thank you so much!

**Comment by YFforever2022** [comment]
> Hi everyone! we found that this problem has been fixed in ultralytics v8.1.41 ([ultralytics/ultralytics#9453](https://github.com/ultralytics/ultralytics/pull/9453)), but yolov10 is based on v8.1.34. So we fixed this manually in our codebase. Please update the code to the latest version. Thank you so much!

Hello, just now, I downloaded the latest version of the code, but still can't successfully resume, Windows 10 system

**Comment by babakbch** [comment]
Hi all
While the resume problem is resolved the optimizer resets to default (auto) and resets the lr and momentum

**Comment by babakbch** [comment]
> ![Screenshot from 2024-09-10 08-44-37](https://private-user-images.githubusercontent.com/71264119/365944266-c0db3363-bb1b-4a03-9524-9c1d286f0238.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NzIyMjYsIm5iZiI6MTcyNTk3MTkyNiwicGF0aCI6Ii83MTI2NDExOS8zNjU5NDQyNjYtYzBkYjMzNjMtYmIxYi00YTAzLTk1MjQtOWMxZDI4NmYwMjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDEyMzg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhOTBkYjIxODQ4NjE2OTQ5MDA1OGEwMmIwNWY4MDZkYzg3NjY1NjU2NzkyZjc1MDc4OTA2OWFiOTYyZWE2NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n_hjYT0G7eg7brmN4XnHJLOtEKMaRjxwHmnpj_CUYtY) ![Screenshot from 2024-09-10 08-44-29](https://private-user-images.githubusercontent.com/71264119/365944277-856104ec-fcdb-4c8c-94ab-1b0a52c1b3ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NzIyMjYsIm5iZiI6MTcyNTk3MTkyNiwicGF0aCI6Ii83MTI2NDExOS8zNjU5NDQyNzctODU2MTA0ZWMtZmNkYi00YzhjLTk0YWItMWIwYTUyYzFiM2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDEyMzg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMWM1ZGE0YTRlOGNiZDQ1NzgxNjAwYWQ0MDY1ZGNkMDE5ZTBkYmYzZTJmMzUyY2JiZTc2OGE3NzZiNDQ0YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4j2NL4yNwCr6Ge5YGrACSIz1xrWe4u_EcbmMfk3Ogto) Hi all While the resume problem is resolved the optimizer resets to default (auto) and resets the lr and momentum. ALthough the optimizer stat is being written to the checkpoint, it cannot be loaded when resuming training, so the trend of parameters changes and in my case losses start to rise. And also the epoch number starts from 1 rather than continue.


So I just had to make sure the optimizer state isn't stripped from the checkpoints and now it's working properly
